# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui\borderTaskbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 138)
#         MainWindow.setStyleSheet("*{\n"
# "    \n"
# "    background-color: rgb(0, 0, 0);\n"
# "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.borderT = QtWidgets.QWidget(self.centralwidget)
        self.borderT.setStyleSheet("*{\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 0, 0);\n"
"     border: 4px solid rgb(255, 255, 255);\n"
"}")
        self.borderT.setObjectName("borderT")
        self.gridLayout.addWidget(self.borderT, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
